deepsite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^diabetics/', include('diabetics.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', RedirectView.as_view(url='/diabetics/uploads/', permanent=True)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

diabetics/urls.py
from django.conf.urls import url
from . import views


app_name = 'diabetics'
urlpatterns = [
    # ex: /diabetics/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # ex: /upload/
    url(r'^uploads/$', views.UploadsView.as_view(), name='uploads'),
    url(r'^delete/(?P<pk>\d+)/$', views.DeleteView.as_view(), name='delete'),
    # ex: /diabetics/5/
    url(r'^(?P<imagename_id>[0-9]+)/$', views.individual, name='individual'),
    # ex: /diabetics/list_view/
    url(r'^list_view/$', views.ListView.as_view(), name='list_view'),
    # ex: /diabetics/summary/
    url(r'^summary/$', views.summary, name='summary'),

]

diabetics/models.py
from django.db import models
from django.dispatch import receiver
from django.utils.translation import ugettext_lazy as _
import os

# Create your models here.
class ImageName(models.Model):

    def get_image_path(self, filename):
        return filename

    imagename = models.CharField(max_length=200)
    result = models.CharField(max_length=20, null=True)       
    image = models.ImageField(upload_to=get_image_path, null=True)    
    
    def __str__(self):
        return self.imagename + ": " + self.result

class Severity(models.Model):
    imagename = models.ForeignKey(ImageName, on_delete=models.CASCADE)
    nodr = models.DecimalField(max_digits=20, decimal_places=15)
    mild = models.DecimalField(max_digits=20, decimal_places=15)
    moderate = models.DecimalField(max_digits=20, decimal_places=15)
    severe = models.DecimalField(max_digits=20, decimal_places=15)
    proliferative = models.DecimalField(max_digits=20, decimal_places=15)

    def __str__(self):
        return str(self.imagename) + "\n" \
                "No DR: " + str(self.nodr) + "\n"\
                "Mild: " + str(self.mild) + "\n"\
                "Moderate: " + str(self.moderate) + "\n"\
                "Severe: " + str(self.severe) + "\n"\
                "Proliferative: " + str(self.proliferative)

# These two auto-delete files from filesystem when they are unneeded:
@receiver(models.signals.post_delete, sender=ImageName)
def auto_delete_file_on_delete(sender, instance, **kwargs):
    """Deletes file from filesystem
    when corresponding `MediaFile` object is deleted.
    """
    if instance.image:
        if os.path.isfile(instance.image.path):
            os.remove(instance.image.path)

@receiver(models.signals.pre_save, sender=ImageName)
def auto_delete_file_on_change(sender, instance, **kwargs):
    """Deletes file from filesystem
    when corresponding `MediaFile` object is changed.
    """
    if not instance.pk:
        return False

    try:
        old_file = ImageName.objects.get(pk=instance.pk).image
    except ImageName.DoesNotExist:
        return False

    new_file = instance.image
    if not old_file == new_file:
        if os.path.isfile(old_file.path):
            os.remove(old_file.path)

diabetics/forms.py
from django import forms

class ImageUploadForm(forms.Form):
    '''Image upload form.'''
    image = forms.ImageField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

diabetics/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse, reverse_lazy
from django.views import generic
from django.template import loader
import json

from .models import ImageName
from .forms import ImageUploadForm

class IndexView(generic.ListView):
    template_name = 'diabetics/index.html'
    context_object_name = 'latest_images_list'

    def get_queryset(self):
        '''Return the last three uploaded images.'''
        return ImageName.objects.order_by('imagename')[:3]    

class UploadsView(generic.edit.FormView):
    form_class = ImageUploadForm
    template_name = 'diabetics/uploads.html'  
    success_url = '../list_view' # Replace with your URL or reverse().

    def post(self, request, *args, **kwargs):
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        files = request.FILES.getlist('image')
        if form.is_valid():
            for f in files:
                new = ImageName(image = f,
                                imagename = f)
                new.save()

            return self.form_valid(form)
        else:
            return self.form_invalid(form)
    
    def get_queryset(self):
        '''Return the last three uploaded images.'''
        return ImageName.objects.order_by('imagename')[:3]

class DeleteView(generic.edit.DeleteView):
    model = ImageName
    success_url = '../../list_view'
    template_name = 'diabetics/delete.html'
  

def individual(request, imagename_id):
    '''Return the specified instance of ImageName.'''
    image = get_object_or_404(ImageName, pk=imagename_id)
    # Get next image or the first image if current image is the last one.
    try:
        next_image = ImageName.objects.get(pk=str(int(imagename_id) + 1))
    except ImageName.DoesNotExist:
        next_image = ImageName.objects.order_by('imagename')[0]
    # Get previous image or the last image if current image is the first one.
    try:
        pre_image = ImageName.objects.get(pk=str(int(imagename_id) - 1))
    except ImageName.DoesNotExist:
        pre_image = ImageName.objects.order_by('imagename').reverse()[0]
    context = {'image': image,
               'next_image': next_image,
               'pre_image': pre_image}
               
    return render(request, 'diabetics/individual.html', context)

class ListView(generic.ListView):
    template_name = 'diabetics/list_view.html'
    context_object_name = 'images_list'

    def get_queryset(self):
        return ImageName.objects.all()    

def summary(request):
    all_severe = ImageName.objects.all()
    result = {"No DR": 0,
              "Mild": 0,
              "Moderate": 0,
              "Severe": 0,
              "Proliferative DR": 0}
    for i in all_severe:
        result[i.result] += 1
        
    return render(request, 'diabetics/summary.html', {'result': json.dumps(result)})

diabetics/templates/diabetics/individual.html
<!DOCTYPE html>
<html>
<title>Individual Result</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
<link href="http://fonts.googleapis.com/css?family=Raleway" rel="stylesheet" type="text/css">
{% load static %}
<style>
body {font-family: "Lato", sans-serif}
body, html {
    color: #FEFEFE;
    background-color: #000;
    
}
.w3-row img {margin-bottom: -8px}

input[type="button"], input[type="submit"], button
{
     background-color: white;
     background-image: url(image/build_button.png);
     background-position: center center;
     border-radius: 20px;
     padding: 15px 32px;
     display: inline-block;
     font-size: 20px;
     width: 250px;
     transition: all 0.5s;
     cursor: pointer;
}
.button span {
  cursor: pointer;
  display: inline-block;
  position: relative;
  transition: 0.5s;
}

.button span:after {
  content: '\00bb';
  position: absolute;
  opacity: 0;
  top: 0;
  right: -20px;
  transition: 0.5s;
}

.button:hover span {
  padding-right: 25px;
}

.button:hover span:after {
  opacity: 1;
  right: 0;
}

</style>

<body>

<!-- !PAGE CONTENT! -->
<div class="w3-content" style="max-width:1500px">

  <!-- Header -->
  <header class="w3-container w3-xlarge w3-padding-24">
    <a href="{% url 'diabetics:individual' pre_image.id %}" class="w3-btn w3-hover-white w3-round-large"> << PREVIOUS </a>
      <a href="{% url 'diabetics:index' %}" class="w3-btn w3-hover-white w3-round-large">HOME</a>
    <a href="{% url 'diabetics:individual' next_image.id %}" class="w3-right w3-btn w3-hover-white w3-round-large"> NEXT >> </a>
  </header>
  
  
  <div class="w3-row">
    <!-- Photo -->
    <div class="w3-col m6 w3-center w3-padding-large">
      <h1 class="w3-center">{{ image.imagename }}</h1>
      <img src="{{ image.image.url }}" style="width:100%">
    </div>
    <!-- Classification Results -->
    <div class="w3-col m6 w3-center w3-padding-large">
      <h1 class="w3-center">{{ image.result }}</h1>
      {% if image.result == 'No DR' %}
        <img src="{% static 'diabetics/images/icon/No DR.png' %}" class="w3-center">
         <p>This eye has no DR! Congrat! Keep Going! <br> For more information about preventing DR. see <a href="http://www.webmd.com/diabetes/tc/diabetic-retinopathy-prevention"><b>here. </b></a></p>
      {% elif image.result == 'Mild' %}
        <img src="{% static 'diabetics/images/icon/Mild.png' %}" class="w3-center">
        <p>You should go to see your doctor for more detailed check. <br> For more information about preventing DR. see <a href="http://www.webmd.com/diabetes/tc/diabetic-retinopathy-prevention"><b>here. </b></a></p>
      {% elif image.result == 'Moderate' %}
        <img src="{% static 'diabetics/images/icon/Moderate.png' %}" class="w3-center">
        <p> <b style="color:red">Warning!</b> You should contact your doctors for <a href="http://www.nhs.uk/Conditions/Diabetic-retinopathy/Pages/Treatment.aspx">treatment!</a></p>
      {% elif image.result == 'Severe' %}
        <img src="{% static 'diabetics/images/icon/Severe.png' %}" class="w3-center">
        <p> <b style="color:red">Danger! </b> Go to see your doctor!!<br> <a href="https://www.google.com.tw/maps/search/hospital/" style="color:red">Hospitals.</a></p>
      {% elif image.result == 'Proliferative DR' %}
        <img src="{% static 'diabetics/images/icon/Proliferative DR.png' %}" class="w3-center">
        <p> <b style="color:red">Treat Immediately!</b></p>
      {% else %}
        <p>Cannot classified by our CNN model !!</p>
      {% endif %}    
    </div>    

  </div> 
</div>
  
  
<!-- Footer --><!--
<footer class="w3-grey w3-padding-32 w3-center">
  <div class="w3-row">
      <div class="w3-half">
        <a href="{% url 'diabetics:list_view' %}" class="button"><button class="button"><span>View All</span></button></a>
      </div>
      <div class="w3-half">
        <a href="{% url 'diabetics:summary' %}"><button class="button"><span>Summary</span></button></a>
      </div>
  </div>

  <p>Powered by <a href="http://www.w3schools.com/w3css/default.asp" target="_blank" class="w3-hover-text-green">w3.css</a></p>
</footer>
-->
<script>
$(document).ready(function() {

    var table = $('#table');

    // Table bordered
    $('#table-bordered').change(function() {
        var value = $( this ).val();
        table.removeClass('table-bordered').addClass(value);
    });

    // Table striped
    $('#table-striped').change(function() {
        var value = $( this ).val();
        table.removeClass('table-striped').addClass(value);
    });
  
    // Table hover
    $('#table-hover').change(function() {
        var value = $( this ).val();
        table.removeClass('table-hover').addClass(value);
    });

    // Table color
    $('#table-color').change(function() {
        var value = $(this).val();
        table.removeClass(/^table-mc-/).addClass(value);
    });
});

// jQuery’s hasClass and removeClass on steroids
// by Nikita Vasilyev
// https://github.com/NV/jquery-regexp-classes
(function(removeClass) {

	jQuery.fn.removeClass = function( value ) {
		if ( value && typeof value.test === "function" ) {
			for ( var i = 0, l = this.length; i < l; i++ ) {
				var elem = this[i];
				if ( elem.nodeType === 1 && elem.className ) {
					var classNames = elem.className.split( /\s+/ );

					for ( var n = classNames.length; n--; ) {
						if ( value.test(classNames[n]) ) {
							classNames.splice(n, 1);
						}
					}
					elem.className = jQuery.trim( classNames.join(" ") );
				}
			}
		} else {
			removeClass.call(this, value);
		}
		return this;
	}

})(jQuery.fn.removeClass);
</script>
 
</body>
</html>

diabetics/templates/diabetics/list_view.html
<!DOCTYPE html>
<html>
<title>List View</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'diabetics/list_style.css' %}" />
<body>
<body>
<!-- Navbar (sit on top) -->
<div class="w3-top" id="top">
  <ul class="w3-navbar" id="myNavbar">
    <li class="w3-hide-medium w3-hide-large w3-opennav w3-right">
      <a class="w3-hover-black" href="javascript:void(0);" onclick="toggleFunction()" title="Toggle Navigation Menu">
        <i class="fa fa-bars"></i>
      </a>
    </li>
       <li class="w3-align"><a href="{% url 'diabetics:index' %}" class="w3-button">HOME</a></li>
       <li class="w3-align"><a href="#list" class="w3-button">Top</a></li>
      <!-- <li class="w3-align"><a href="{% url 'diabetics:summary' %}" class="w3-button">Summary</a></li> -->
  </ul>
</div>

<div id="list">
  <h1>  Uploaded Retina Photos</h1>
  <h2>Table of results of your images.</h2>
  
  <!-- Responsive table starts here -->
  <!-- For correct display on small screens you must add 'data-title' to each 'td' in your table -->
  <div class="table-responsive-vertical shadow-z-1">
  <!-- Table starts here -->
  <table id="table" class="table table-hover table-mc-light-blue table-bordered">
      <thead>
        <tr>
          <th>ID</th>
          <th>Name</th>
          <th>Detail</th>
          <th>Result</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
        <tr>
        {% for image in images_list %}
        <tr>
          <td data-title="ID">{{ image.id }}</td>
          <td data-title="Name">{{ image.imagename }}</td>
          <td data-title="Detail">
            <a href="{% url 'diabetics:individual' image.id %}" target="_blank"><i class="glyphicon glyphicon-file"></i></a>
          </td>
          <td data-title="Result">{{ image.result }}
             {% if image.result == 'No DR' %}
               <img src="{% static 'diabetics/images/icon/No DR.png' %}" width="40" height="40">
             {% elif image.result == 'Mild' %}
               <img src="{% static 'diabetics/images/icon/Mild.png' %}" width="40" height="40">
             {% elif image.result == 'Moderate' %}
               <img src="{% static 'diabetics/images/icon/Moderate.png' %}" width="40" height="40">
             {% elif image.result == 'Severe' %}
               <img src="{% static 'diabetics/images/icon/Severe.png' %}" width="40" height="40">
             {% elif image.result == 'Proliferative DR' %}
               <img src="{% static 'diabetics/images/icon/Proliferative DR.png' %}" width="40" height="40">
             {% else %}
               <p>Cannot classified by our CNN model !!</p>
             {% endif %}    
          </td>
           <td data-title="Delete"><a href="{% url 'diabetics:delete' pk=image.pk %}"><i class="fa fa-trash"></i></a></td>
        </tr>
        {% endfor %}
        </tr>
      </tbody>
    </table>
  </div>
  <!-- Footer -->
<footer class="w3-padding-32 w3-center">
  <div class="w3-row">
      <div class="w3-half">
 <!--       <a href="{% url 'diabetics:uploads' %}" class="button"><button class="button"><span>Upload</span></button></a> -->
      </div>
      <div class="w3-half">
   <!--     <a href="{% url 'diabetics:summary' %}"><button class="button"><span>Summary</span></button></a> -->
      </div>
  </div>
<!--  <p>Powered by <a href="http://codepen.io/zavoloklom/full/IGkDz/" target="_blank" class="w3-hover-text-green">Sergey Kupletsky</a></p>-->
</footer>
</div>

<script>
$(document).ready(function() {

    var table = $('#table');

    // Table bordered
    $('#table-bordered').change(function() {
        var value = $( this ).val();
        table.removeClass('table-bordered').addClass(value);
    });

    // Table striped
    $('#table-striped').change(function() {
        var value = $( this ).val();
        table.removeClass('table-striped').addClass(value);
    });
  
    // Table hover
    $('#table-hover').change(function() {
        var value = $( this ).val();
        table.removeClass('table-hover').addClass(value);
    });

    // Table color
    $('#table-color').change(function() {
        var value = $(this).val();
        table.removeClass(/^table-mc-/).addClass(value);
    });
});

// jQuery’s hasClass and removeClass on steroids
// by Nikita Vasilyev
// https://github.com/NV/jquery-regexp-classes
(function(removeClass) {

	jQuery.fn.removeClass = function( value ) {
		if ( value && typeof value.test === "function" ) {
			for ( var i = 0, l = this.length; i < l; i++ ) {
				var elem = this[i];
				if ( elem.nodeType === 1 && elem.className ) {
					var classNames = elem.className.split( /\s+/ );

					for ( var n = classNames.length; n--; ) {
						if ( value.test(classNames[n]) ) {
							classNames.splice(n, 1);
						}
					}
					elem.className = jQuery.trim( classNames.join(" ") );
				}
			}
		} else {
			removeClass.call(this, value);
		}
		return this;
	}

})(jQuery.fn.removeClass);

// Change style of navbar on scroll
window.onscroll = function() {myFunction()};
function myFunction() {
    var navbar = document.getElementById("myNavbar");
    if (document.body.scrollTop > 100 || document.documentElement.scrollTop > 100) {
        navbar.className = "w3-navbar" + " w3-card-2" + " w3-animate-top" + " w3-black";
    } else {
        navbar.className = navbar.className.replace(" w3-card-2 w3-animate-top w3-black", "");
    }
};
</script>

</body>

diabetics/templates/diabetics/summary.html
<!--

<!DOCTYPE html>
<html>
<title>Summary</title>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
<link href="http://fonts.googleapis.com/css?family=Raleway" rel="stylesheet" type="text/css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.5/d3.min.js"></script>
<script src="http://labratrevenge.com/d3-tip/javascripts/d3.tip.v0.6.3.js"></script>
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'diabetics/summary_style.css' %}" />

<body>
-->

<!-- !PAGE CONTENT! -->
<!--
<div class="w3-content" style="max-width:1500px">
-->
  <!-- Header --><!--
  <header class="w3-container w3-xlarge w3-padding-24">
      <a href="{% url 'diabetics:index' %}" class="w3-btn w3-hover-white w3-round-large">HOME</a>
    <a href="{% url 'diabetics:list_view' %}" class="w3-right w3-btn w3-hover-white w3-round-large">View All</a>
  </header>
-->
  <!-- Summary -->
<!--
  <div class="w3-row w3-center">
      <div class="w3-center">
          <!-- Bar-chart of total images in database --><!--
          <h1 style="color:white;margin-left:30px;">Total Count of Images</h1>
          <svg id="chartarea"></svg> -->
<!--
  <script type="text/javascript">
        var data = d3.entries({{ result|safe }});
        barchart(data);

        function barchart(data){
                var margin = {top: 40, right: 20, bottom: 30, left: 40},
                    width = 700 - margin.left - margin.right,
                    height = 500 - margin.top - margin.bottom;
                var x = d3.scale.ordinal()
                          .rangeRoundBands([0, width], .1);
                var y = d3.scale.linear()
                          .range([height, 0]);
                var xAxis = d3.svg.axis()
                              .scale(x)
                              .orient("bottom");
                var yAxis = d3.svg.axis()
                              .scale(y)
                              .orient("left")
                var color = d3.scale.category20c();
                var tip = d3.tip()
                            .attr('class', 'd3-tip')
                            .offset([-10, 0])
                            .html(function(d) {return d.key+": <span style='color:white'>"+d.value+"</span>";});
                // construc svg
	        var svg = d3.select("#chartarea")
                            .attr("width", width + margin.left + margin.right)
                            .attr("height", height + margin.top + margin.bottom)
                            .append("g")
                            .attr("transform", "translate(" + margin.left + "," + margin.top + ")");
                svg.call(tip);
        
                var dvalue = data.map(function(d){return d.value;});

                x.domain(data.map(function(d){return d.key;}));
		y.domain([0, d3.max(dvalue)]);
                // Add Axis
		svg.append("g")
      		   .attr("class", "x axis")
       		   .attr("transform", "translate(0," + height + ")")
       		   .call(xAxis);
                svg.append("g")
                   .attr("class", "y axis")
                   .call(yAxis)
                  .append("text")
                   .attr("transform", "rotate(-90)")
                   .attr("y", 6)
                   .attr("dy", ".71em")
                   .style("text-anchor", "end")
                   .text("Frequency");
                // paint barchart on svg
		svg.selectAll(".bar")
                   .data(data)
                  .enter().append("rect")
                   .attr("class", "bar")
                   .attr("x", function(d) { return x(d.key); })
                   .attr("width", x.rangeBand())
                   .attr("y", function(d) { return y(d.value); })
                   .attr("height", function(d) { return height - y(d.value); })
                   .on('mouseover', tip.show)
                   .on('mouseout', tip.hide);

                       
	}//end of barchart
	</script>
  </div>
  -->

<!-- End Page Content -->
<!--
</div>

<!-- Footer --><!--
<footer class="w3-center">
  <p>Powered by <a href="http://www.w3schools.com/w3css/default.asp" target="_blank" class="w3-hover-text-blue">w3.css</a></p>
</footer>
 
</body>
</html>
-->

diabetics/templates/diabetics/uploads.html
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>Uploads</title> 
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="http://www.w3schools.com/lib/w3.css">
<link href="http://fonts.googleapis.com/css?family=Raleway" rel="stylesheet" type="text/css">
{% load static %}
<style>
body {font-family: "Lato", sans-serif}
body, html {
    color: #FEFEFE;
    background-color: #000;

}
.w3-row img {margin-bottom: -8px}

input[type="button"], input[type="submit"], button
{
     background-color: white;
     background-image: url(image/build_button.png);
     background-position: center center;
     border-radius: 20px;
     padding: 15px 32px;
     display: inline-block;
     font-size: 20px;
     width: 250px;
     transition: all 0.5s;
     cursor: pointer;
}
.button span {
  cursor: pointer;
  display: inline-block;
  position: relative;
  transition: 0.5s;
}

.button span:after {
  content: '\00bb';
  position: absolute;
  opacity: 0;
  top: 0;
  right: -20px;
  transition: 0.5s;
}

.button:hover span {
  padding-right: 25px;
}

.button:hover span:after {
  opacity: 1;
  right: 0;
}

</style>
  
</head>
<body> 
  <div class="w3-content" style="max-width:1500px">

  <!-- Header -->
  <header class="w3-container w3-xlarge w3-padding-24">
      <a href="{% url 'diabetics:index' %}" class="w3-btn w3-hover-white w3-round-large">HOME</a>
  </header>
  </div>
   <div class="w3-center w3-padding-32">
        <h1 class="w3-center">Upload Retinal Fundus Photos</h1>
         <!-- Upload form. Note enctype attribute! -->
        <form action="{% url 'diabetics:uploads' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p>{{ form.non_field_errors }}</p>
            <p>
                {{ form.image.errors }}
                {{ form.image }}
            </p>
            <p><input type="submit" value="Upload" /></p>
        </form>
    </div>
<!-- Footer --> <!--
<footer class="w3-grey w3-padding-32 w3-center">
  <p>Powered by <a href="http://www.w3schools.com/w3css/default.asp" target="_blank" class="w3-hover-text-green">w3.css</a></p>
</footer>
-->
<script>
$(document).ready(function() {

    var table = $('#table');

    // Table bordered
    $('#table-bordered').change(function() {
        var value = $( this ).val();
        table.removeClass('table-bordered').addClass(value);
    });

    // Table striped
    $('#table-striped').change(function() {
        var value = $( this ).val();
        table.removeClass('table-striped').addClass(value);
    });

    // Table hover
    $('#table-hover').change(function() {
        var value = $( this ).val();
        table.removeClass('table-hover').addClass(value);
    });

    // Table color
    $('#table-color').change(function() {
        var value = $(this).val();
        table.removeClass(/^table-mc-/).addClass(value);
    });
});

// jQuery’s hasClass and removeClass on steroids
// by Nikita Vasilyev
// https://github.com/NV/jquery-regexp-classes
(function(removeClass) {

	jQuery.fn.removeClass = function( value ) {
		if ( value && typeof value.test === "function" ) {
			for ( var i = 0, l = this.length; i < l; i++ ) {
				var elem = this[i];
				if ( elem.nodeType === 1 && elem.className ) {
					var classNames = elem.className.split( /\s+/ );

					for ( var n = classNames.length; n--; ) {
						if ( value.test(classNames[n]) ) {
							classNames.splice(n, 1);
						}
					}
					elem.className = jQuery.trim( classNames.join(" ") );
				}
			}
		} else {
			removeClass.call(this, value);
		}
		return this;
	}

})(jQuery.fn.removeClass);
</script>
 
    </body>
</html> 